### ISSUE TITLE
Remove deprecated description strings in "type" folder

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#11]
The deprecated ~~name,~~ description strings for the hats, pets, mounts etc. are still in the [ultracosmetics/cosmetics/type/](https://github.com/datatags/UltraCosmetics/tree/master/core/src/main/java/be/isach/ultracosmetics/cosmetics/type) folder. Can you remove them entirely or use the messages_en.yml strings instead?

**Comment by datatags** [comment]
Yes, the description strings should be removed, but name has to stay because that's how it finds its configuration block and translation strings.

**Comment by dennishzg** [comment]
Oh yes, not the name of course 😅
