### ISSUE TITLE
generated an exception while executing task 60

### ISSUE THREAD

**Issue by Tmdoofking** [datatags/UltraCosmetics#118]
### Check if the issue is fixed in dev builds

- [ ] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

![image](https://github.com/datatags/UltraCosmetics/assets/70594985/73bd4659-5bdc-4bd8-a777-6a394e84fd67)

### What was supposed to happen?

i dont know

### What happened instead?

![image](https://github.com/datatags/UltraCosmetics/assets/70594985/9894b98a-cb5d-4c4f-b18b-40d9357351a9)

### What version of UltraCosmetics are you using? Do not say 'latest'.

3.3

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

paper-1.19.2-183

### What plugins do you have installed?

![image](https://github.com/datatags/UltraCosmetics/assets/70594985/69aff82b-a729-4955-9625-0eae50dc682a)

**Comment by Tmdoofking** [comment]
it somehow spam this now
![image](https://github.com/datatags/UltraCosmetics/assets/70594985/173d6882-0b8e-4f54-841c-006891e208b6)

**Comment by datatags** [comment]
Already fixed in f5d9eca7f724a13d1c558d08fb44e4c3c480e721, use a GitHub actions build for this fix
