### ISSUE TITLE
rocket gadget problem

### ISSUE THREAD

**Issue by serumanooo** [datatags/UltraCosmetics#120]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

idk

### What was supposed to happen?

the rocket gadget should work properly

### What happened instead?

the rocket seems shattered for me when i use it, and for the other players i still on the ground

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.3-RELEASE.jar

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Im using WindSpigot  version 2.1.2 [maintainer note: MC 1.8.8]

### What plugins do you have installed?

![image](https://github.com/datatags/UltraCosmetics/assets/132185379/218c370f-b640-4163-b0a2-194e0ac60785)
![image](https://github.com/datatags/UltraCosmetics/assets/132185379/3b9edb47-1b96-4600-8bba-d7b818a5497c)
![image](https://github.com/datatags/UltraCosmetics/assets/132185379/4d6c71ad-3662-431c-9840-f3241468c60b)

### Are there any errors in the console or in logs?

no

### Additional information that could be helpful in fixing the problem

when i first installed ultracosmetics, the rocket gadget worked just fine, but now its like i said: the rocket seems shattered for me when i use it, and for the other players i still on the ground

**Comment by datatags** [comment]
When you say "shattered," do you mean the pieces of the rocket don't lift off and the blocks place themselves on the ground? Does this happen every time you use the rocket, or only sometimes?

**Comment by serumanooo** [comment]
> When you say "shattered," do you mean the pieces of the rocket don't lift off and the blocks place themselves on the ground? Does this happen every time you use the rocket, or only sometimes?

yes, and it happens everytime

**Comment by serumanooo** [comment]
@datatags https://youtu.be/XnMdcLgH_hY

**Comment by datatags** [comment]
> @datatags https://youtu.be/XnMdcLgH_hY

I see, would you be able to try on a test server with no other plugins? Or maybe on vanilla Spigot? I tried the rocket gadget on 1.8.8 and it seems to be working fine for me under those circumstances

**Comment by serumanooo** [comment]
> > @datatags https://youtu.be/XnMdcLgH_hY
> 
> I see, would you be able to try on a test server with no other plugins? Or on vanilla Spigot if that doesn't work? I tried the rocket gadget on 1.8.8 and it seems to be working fine for me under those circumstances

Ill try later with other spigot fork and ill also try other things

**Comment by datatags** [comment]
Any luck on figuring this out?

**Comment by datatags** [comment]
Closing due to no response
