### ISSUE TITLE
Broken strings in translations because of new MiniMessage syntax

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#128]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Open all menus

### What was supposed to happen?

No broken strings.

### What happened instead?

A lot of strings in the translations are still broken. Pretty much all languages have broken strings which use the old `&` syntax instead of the new MiniMessage syntax.

The broken strings in the German translation are all marked as "hidden" and "duplicate" but the old approved translations of those strings are still in the messages file. Maybe you have to delete the approved translations of the duplicate strings? 🤔 

You can use Crowdin's advanced filter to quickly find all of the broken strings:

![Screenshot (434)](https://github.com/datatags/UltraCosmetics/assets/33426785/776fa825-afb0-42a2-b5c7-71e9e759c0bc)

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.4-DEV-b3

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)

### What plugins do you have installed?

/

### Are there any errors in the console or in logs?

No

**Comment by datatags** [comment]
Thanks for the tip with the filter, I've gone back through each language and fixed that and #129, and those changes will be applied once #131 is merged!
