### ISSUE TITLE
Missing cosmetics in Pets and Mounts menu

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#130]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Open Pets menu and Mounts menu

### What was supposed to happen?

Show all pets and mounts.

### What happened instead?

I see 41 instead of 73 pets.

I see 18 instead of 22 mounts. MoltenSnake, SlimeSnake, Slime and Spider are missing. (issue with NMS?)

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.4-DEV-b3

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper version git-Paper-132 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb8f2bb)

### What plugins do you have installed?

[01:34:00 INFO]: Server Plugins (33):
[01:34:00 INFO]: Paper Plugins:
[01:34:00 INFO]:  - BKCommonLib
[01:34:00 INFO]: Bukkit Plugins:
[01:34:00 INFO]:  - AdvancedRegionMarket, Autorank, ChatManager, Chunky, ChunkyBorder, CMILib, CoreProtect, DeadChest, DeluxeMenus, DropHeads
[01:34:00 INFO]:  Essentials, EssentialsSpawn, FarmControl, Images, Jobs, LibsDisguises, LuckPerms, Maintenance, MiniMOTD, My_Worlds
[01:34:00 INFO]:  OpenInv, PlaceholderAPI, ProtocolLib, QuickShop, ResourceWorld, SuperVanish, TabList, UltraCosmetics, UltraCosmeticsGUIAddon, Vault
[01:34:00 INFO]:  WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

No

### Additional information that could be helpful in fixing the problem

Log:
`[01:31:52 INFO]: [UltraCosmetics] Loaded NMS support`

**Comment by datatags** [comment]
Is your world in peaceful? UC will hide cosmetics that can't be used due to the world being in peaceful, although there's probably a better way to communicate that

**Comment by dennishzg** [comment]
Yes my world was in peaceful. 🤦 I forgot that I changed it a few days ago because the mobs were annoying me. Thanks! 😿 

It would probably be better if the pets/mounts would still show up in the menus and when you try to use them a message should appear in the chat: "Can't spawn this mob because the world is in peaceful!" something like that.

**Comment by dennishzg** [comment]
Not a bug. Converted to https://github.com/datatags/UltraCosmetics/labels/enhancement issue: #134
