### ISSUE TITLE
Text issue when using /uc toggle

### ISSUE THREAD

**Issue by Jish-The-Third** [datatags/UltraCosmetics#132]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Install the plugin and use /uc toggle (nothing else after that)
2. Look in chat

### What was supposed to happen?

The command was supposed to have the prefix "Cosmetic >" after the command along with the proper usage for the command.

### What happened instead?

It gives weird message data in the chat message.

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.30-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-164 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6813244)

### What plugins do you have installed?

BungeeGuard, CommandPanels, Essentials, LibsDisguises, LuckPerms, MyCommand, Parkour, PlayerNPC, PosCommands, ProtocolLib, PvPManager, SCore, UltraCosmetics, Vault, XConomy

**Comment by datatags** [comment]
I found the issue, but generally if something strange is showing up it's helpful to know exactly what it is
