### ISSUE TITLE
Add i18n support for the messages defined in the config.yml file

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#21]
### Describe the feature and how it would be used

All the messages defined in the config.yml file need to be changed, so that they can be translated on Crowdin. Put those strings in the messages_en.yml file etc.

Example:

https://github.com/datatags/UltraCosmetics/blob/6722f8b6a38f0a40ba4e684ee00f314716752ef9/core/src/main/resources/config.yml#L287-L288

### Are there alternatives?

No

**Comment by dennishzg** [comment]
@datatags Looks like you added this feature. Can I close this issue?

**Comment by datatags** [comment]
Yep, thanks for the reminder 😄

**Comment by dennishzg** [comment]
Feature has been added.
