### ISSUE TITLE
Pig & Strider mount

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#49]
### Describe the feature and how it would be used

Idea for 2 new mounts:

### "Pig" and "Strider":

- Vanilla mechanics.
- Equip both mounts with a saddle.
- Once the mount spawns, the player will be given a "Carrot on a Stick" or "Warped Fungus on a Stick" item to control the mount. The item should behave/work just like the gadgets items (Perhaps we can reuse those functions?). 
- Increase the movement speed of the Pig a little bit.
- Maybe increase the movement speed of the Strider outside of lava? But the main purpose of this mount is to walk on lava.

### Are there alternatives?

No

**Comment by datatags** [comment]
I did think about doing those previously but wasn't sure what to do about the "on a stick" items, but using the gadget slot is a great idea!
