### ISSUE TITLE
New default main menu items

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#61]
### Describe the feature and how it would be used

I have some improvements/suggestions for some of the main menu category items:

- Replace "Death Effects" item with `WITHER_SKELETON_SKULL`
  - Reason: Skulls are associated with death. The diamond sword could mean: Sword Effects, PVP or Combat. The wither skeleton skull looks better than the skeleton skull in my opinion, because of the higher contrast.

- Replace "Particle Effects" item with `BLAZE_POWDER`
  - Reason: The nether star has the enchantment effect by default, which is problematic because UC uses the enchantment effect to highlight equipped cosmetics. Players may think that they have a particle effect equipped because the item is glowing. 2 particle effects have the blaze powder item.

- Replace "Gadgets" item with `IRON_AXE`
  - Reason: The prismarine shard doesn't fit at all in my opinion. The iron axe is a tool that you can actually use or interact with, like a gadget. The gadget "Thor's Hammer" has the iron axe item.

## Preview:

![mainmenuitems](https://user-images.githubusercontent.com/33426785/205800798-2a0718b7-7524-405f-9df3-f25c4725b7da.png)

### Are there alternatives?

.

**Comment by datatags** [comment]
Seems like a good idea! The only thing is I was planning to make it so death effects work both when a player dies and when a player kills another player/mob, so it would signify PvP and combat. Do you think a sword would be fine then, or a wither skull would be best?

**Comment by dennishzg** [comment]
I think a wither skull would be better because it's still the death event that triggers the death effects. 

>  I was planning to make it so death effects work both when a player dies and when a player kills another player/mob

Does player A's death effect spawn at player B's location if A kills B? If so, the death effects will definitely overlap when both players have a death effect equipped.
Or does the death effect spawn at the location of player A? The death effects could overlap when both players fight in close combat.

Mobs could be a bit problematic too if you kill a lot of mobs at once, for example in an [enderman xp farm](https://youtu.be/tMgBbvH7AhY?t=427). I hope that doesn't cause any lags. You probably have to add a cooldown for the death effects.

I prefer the current implementation of the death effects.
