### ISSUE TITLE
Enderpearls, eggs etc. trigger projectile effects

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#65]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Equip any projectile effect.
2. Throw an Egg, Enderpearl or launch a Firework Rocket.

### What was supposed to happen?

No projectile effects should appear when I use those items. Only the Bow, Crossbow and Trident should trigger projectile effects.

### What happened instead?

Projectile effects appeared. 

### What version of UltraCosmetics are you using? Do not say 'latest'.

(2e0f5b5d1f92289162754ab527cfd157cbfe1f00) UltraCosmetics-3.0-DEV-b2

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-296 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: f1583fc)

### What plugins do you have installed?

Plugins (8): Essentials, LibsDisguises, LuckPerms, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

No

**Comment by datatags** [comment]
Why should projectile effects be limited to weapons? I could see a config option for this being a good idea, but I can't think of any inherent issues with snowballs or eggs working as projectiles.

**Comment by dennishzg** [comment]
Why should eggs have projectile effects? I think it looks strange.

The Minecraft Wiki says "Snowballs are throwable combat items." and you use snowballs to destroy end crystals. I forgot about that. Projectile effects for snowballs are okay. 👍
