### ISSUE TITLE
The particle effects alternative effects shouldn't block the players view

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#81]
### Describe the feature and how it would be used

The particle effects alternative effects spawn inside of the player. This is bad because some particles will spawn in front of the players face, which is really annoying and it's blocking the view.

Example:

https://user-images.githubusercontent.com/33426785/210161041-ff91d638-46c3-456c-accf-e518ac534651.mp4

---

~~The particles should spawn behind the player.~~

All alternative effects trails (except CrushedCandyCane) have this issue:

https://github.com/datatags/UltraCosmetics/blob/f902e0e9bb560a52df912614d44d871eff91fdb0/core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffect.java#L86

https://github.com/datatags/UltraCosmetics/blob/f902e0e9bb560a52df912614d44d871eff91fdb0/core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffectAngelWings.java#L49

https://github.com/datatags/UltraCosmetics/blob/f902e0e9bb560a52df912614d44d871eff91fdb0/core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffectBloodHelix.java#L53

https://github.com/datatags/UltraCosmetics/blob/f902e0e9bb560a52df912614d44d871eff91fdb0/core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffectMagicalRods.java#L80

https://github.com/datatags/UltraCosmetics/blob/f902e0e9bb560a52df912614d44d871eff91fdb0/core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffectRainbowWings.java#L44

### Are there alternatives?

No

**Comment by datatags** [comment]
Related (request from Discord):
> It could be nice to have a single particle at the bottom of the feet, like a trail. So they don't disturb the vision if you know what I mean

**Comment by dennishzg** [comment]
Good idea, that would look better. A config option isn't necessary.

**Comment by dennishzg** [comment]
Or maybe a smaller version of the current effect? 3 or 4 particles, particles closer together, smaller, behind the player at the bottom of the feet.
Looks better in my opinion.
