### ISSUE TITLE
Treasure chest loot category text looks different

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#82]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Open a treasure chest.
2. Look at the treasure chest loot category text.

![Screenshot (29)](https://user-images.githubusercontent.com/33426785/210686962-fd7865fc-d7b4-41a6-a7e8-49ecc70bb181.png)

### What was supposed to happen?

The treasure chest loot category text should look the same.

### What happened instead?

The text looks different. "Pet" has a ":" at the end.

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.0-DEV-b4

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-345 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e498dda)

### What plugins do you have installed?

Plugins (8): Essentials, LibsDisguises, LuckPerms, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

No

**Comment by datatags** [comment]
Fixed in Crowdin; I'll close this once the change makes it into `master`

**Comment by datatags** [comment]
Fixed in f5f0ccbcab5bd94dea5968f78c7c064698908a56
