### ISSUE TITLE
Players can take cosmetic armour

### ISSUE THREAD

**Issue by starrider23** [datatags/UltraCosmetics#90]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Equip a cosmetic armour.
2. Replace the armour piece with one in your inventory.
3. Leave and rejoin and you now have a permanent piece of the cosmetic armour.

### What was supposed to happen?

You shouldn't be able to replace the armour piece.

### What happened instead?

You are able to replace the armour piece.

### What version of UltraCosmetics are you using? Do not say 'latest'.

3.0-DEV-b4 : But has been in every version I have used.

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper-377

### What plugins do you have installed?

![image](https://user-images.githubusercontent.com/83950434/212474401-6bdd81e2-97ac-4e52-8870-01fa07800f8c.png)
![image](https://user-images.githubusercontent.com/83950434/212474420-3f9dbc7e-094c-430b-ab47-537f31be88f4.png)
![image](https://user-images.githubusercontent.com/83950434/212474445-5ee1aec0-db93-4bed-8987-f63447ef5b90.png)

### Are there any errors in the console or in logs?

No

**Comment by datatags** [comment]
I'm not able to replace the armor piece on my test server, could you try on your test server with no other plugins?

**Comment by datatags** [comment]
Hello, any update on this? Have you tried on a test server with no other plugins?

**Comment by datatags** [comment]
Closing due to no response.
